### ISSUE TITLE
[Epic] Generate project with Mason

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#230]
## Why

According to what we achieved in [Create a POC for mason lib to generate template project's features](https://github.com/nimblehq/flutter_templates/issues/128), we can start on the following steps to build a new "project-generating" mechanism with [Mason](https://pub.dev/packages/mason_cli) to replace [the existing legacy and complex Python script](https://github.com/nimblehq/flutter_templates/blob/develop/scripts/setup.py) which is not familiar with a Flutter or mobile dev to maintain and contribute. The idea is to apply Mason to restructure the template in a "configurable way" and allow us to move some features to be "optional features" when generating the new project.
 
## Who Benefits?

Developers

```[tasklist]
### Tasks
- [ ] https://github.com/nimblehq/flutter-templates/issues/128
- [ ] https://github.com/nimblehq/flutter-templates/issues/155
- [ ] https://github.com/nimblehq/flutter-templates/issues/156
- [ ] https://github.com/nimblehq/flutter-templates/issues/157
- [ ] https://github.com/nimblehq/flutter-templates/issues/158
- [ ] https://github.com/nimblehq/flutter-templates/issues/162
- [ ] https://github.com/nimblehq/flutter-templates/issues/177
- [ ] https://github.com/nimblehq/flutter-templates/issues/184
- [ ] https://github.com/nimblehq/flutter-templates/issues/159
- [ ] https://github.com/nimblehq/flutter-templates/issues/188
- [ ] https://github.com/nimblehq/flutter-templates/issues/160
- [ ] https://github.com/nimblehq/flutter-templates/issues/200
- [ ] https://github.com/nimblehq/flutter-templates/issues/210
```
